/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CategoryInput: typeof import('./src/components/inputs/CategoryInput.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    LoadingFullPage: typeof import('./src/components/indicators/LoadingFullPage.vue')['default']
    MarketPlace: typeof import('./src/components/MarketPlace.vue')['default']
    PriceInput: typeof import('./src/components/inputs/PriceInput.vue')['default']
    PrimaryButton: typeof import('./src/components/buttons/PrimaryButton.vue')['default']
    ProductsList: typeof import('./src/components/lists/ProductsList.vue')['default']
    RatingInput: typeof import('./src/components/inputs/RatingInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/inputs/SearchInput.vue')['default']
    SelectInput: typeof import('./src/components/inputs/SelectInput.vue')['default']
    SelectInputBase: typeof import('./src/components/inputs/SelectInputBase.vue')['default']
    SellerIndicator: typeof import('./src/components/indicators/SellerIndicator.vue')['default']
    ShoppingBagIndicator: typeof import('./src/components/indicators/ShoppingBagIndicator.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
